package com.example.woof.dataResource

import com.example.woof.R
import com.example.woof.data.Campeon

class CampeonDataSource {

    fun getCampeones() : List<Campeon> {
        return listOf(
            Campeon(
                nombre = R.string.champ_name_1,
                imagen = R.drawable.yone,
                descripcion = R.string.champ_description_1,
                pInf = R.string.pInf_1,
                qInf = R.string.qInf_1,
                wInf = R.string.wInf_1,
                eInf = R.string.eInf_1,
                rInf = R.string.rInf_1,
                pImg = R.drawable.yone_p,
                qImg = R.drawable.yone_q,
                wImg = R.drawable.yone_w,
                eImg = R.drawable.yone_e,
                rImg = R.drawable.yone_r,
                skinFoto = R.drawable.yone_sombratinta,
                skinNombre = R.string.skin1
            ),
            Campeon(
                nombre = R.string.champ_name_3,
                imagen = R.drawable.yasuo,
                descripcion = R.string.champ_description_3,
                pInf = R.string.pInf_3,
                qInf = R.string.qInf_3,
                wInf = R.string.wInf_3,
                eInf = R.string.eInf_3,
                rInf = R.string.rInf_3,
                pImg = R.drawable.yasuo_p,
                qImg = R.drawable.yasuo_q,
                wImg = R.drawable.yasuo_w,
                eImg = R.drawable.yasuo_e,
                rImg = R.drawable.yasuo_r,
                skinFoto = R.drawable.yasuo_skin,
                skinNombre = R.string.skin2
            ),
            Campeon(
                nombre = R.string.champ_name_4,
                imagen = R.drawable.senna,
                descripcion = R.string.champ_description_4,
                pInf = R.string.pInf_4,
                qInf = R.string.qInf_4,
                wInf = R.string.wInf_4,
                eInf = R.string.eInf_4,
                rInf = R.string.rInf_4,
                pImg = R.drawable.senna_p,
                qImg = R.drawable.senna_q,
                wImg = R.drawable.senna_w,
                eImg = R.drawable.senna_e,
                rImg = R.drawable.senna_r,
                skinFoto = R.drawable.senna_skin,
                skinNombre = R.string.skin3
            ),
            Campeon(
                nombre = R.string.champ_name_5,
                imagen = R.drawable.kayn,
                descripcion = R.string.champ_description_5,
                pInf = R.string.pInf_5,
                qInf = R.string.qInf_5,
                wInf = R.string.wInf_5,
                eInf = R.string.eInf_5,
                rInf = R.string.rInf_5,
                pImg = R.drawable.kayn_p,
                qImg = R.drawable.kayn_q,
                wImg = R.drawable.kayn_w,
                eImg = R.drawable.kayn_e,
                rImg = R.drawable.kayn_r,
                skinFoto = R.drawable.kayn_skin,
                skinNombre = R.string.skin4
            ),
            Campeon(
                nombre = R.string.champ_name_6,
                imagen = R.drawable.twistedfate,
                descripcion = R.string.champ_description_6,
                pInf = R.string.pInf_6,
                qInf = R.string.qInf_6,
                wInf = R.string.wInf_6,
                eInf = R.string.eInf_6,
                rInf = R.string.rInf_6,
                pImg = R.drawable.twistedfate_p,
                qImg = R.drawable.twistedfate_q,
                wImg = R.drawable.twistedfate_w,
                eImg = R.drawable.twistedfate_e,
                rImg = R.drawable.twistedfate_r,
                skinFoto = R.drawable.twistedfate_skin,
                skinNombre = R.string.skin5
            ),
            Campeon(
                nombre = R.string.champ_name_7,
                imagen = R.drawable.akali,
                descripcion = R.string.champ_description_7,
                pInf = R.string.pInf_7,
                qInf = R.string.qInf_7,
                wInf = R.string.wInf_7,
                eInf = R.string.eInf_7,
                rInf = R.string.rInf_7,
                pImg = R.drawable.akali_p,
                qImg = R.drawable.akali_q,
                wImg = R.drawable.akali_w,
                eImg = R.drawable.akali_e,
                rImg = R.drawable.akali_r,
                skinFoto = R.drawable.akali_skin,
                skinNombre = R.string.skin6
            ),
            Campeon(
                nombre = R.string.champ_name_8,
                imagen = R.drawable.shyvana,
                descripcion = R.string.champ_description_8,
                pInf = R.string.pInf_8,
                qInf = R.string.qInf_8,
                wInf = R.string.wInf_8,
                eInf = R.string.eInf_8,
                rInf = R.string.rInf_8,
                pImg = R.drawable.shyvana_p,
                qImg = R.drawable.shyvana_q,
                wImg = R.drawable.shyvana_w,
                eImg = R.drawable.shyvana_e,
                rImg = R.drawable.shyvana_r,
                skinFoto = R.drawable.shyvana_skin,
                skinNombre = R.string.skin7
            ),
            Campeon(
                nombre = R.string.champ_name_9,
                imagen = R.drawable.soraka,
                descripcion = R.string.champ_description_9,
                pInf = R.string.pInf_9,
                qInf = R.string.qInf_9,
                wInf = R.string.wInf_9,
                eInf = R.string.eInf_9,
                rInf = R.string.rInf_9,
                pImg = R.drawable.soraka_p,
                qImg = R.drawable.soraka_q,
                wImg = R.drawable.soraka_w,
                eImg = R.drawable.soraka_e,
                rImg = R.drawable.soraka_r,
                skinFoto = R.drawable.soraka_skin,
                skinNombre = R.string.skin8
            ),
            Campeon(
                nombre = R.string.champ_name_10,
                imagen = R.drawable.anivia,
                descripcion = R.string.champ_description_10,
                pInf = R.string.pInf_10,
                qInf = R.string.qInf_10,
                wInf = R.string.wInf_10,
                eInf = R.string.eInf_10,
                rInf = R.string.rInf_10,
                pImg = R.drawable.anivia_p,
                qImg = R.drawable.anivia_q,
                wImg = R.drawable.anivia_w,
                eImg = R.drawable.anivia_e,
                rImg = R.drawable.anivia_r,
                skinFoto = R.drawable.anivia_skin,
                skinNombre = R.string.skin9
            ),
            Campeon(
                nombre = R.string.champ_name_2,
                imagen = R.drawable.corki,
                descripcion = R.string.champ_description_2,
                pInf = R.string.pInf_2,
                qInf = R.string.qInf_2,
                wInf = R.string.wInf_2,
                eInf = R.string.eInf_2,
                rInf = R.string.rInf_2,
                pImg = R.drawable.corki_p,
                qImg = R.drawable.corki_q,
                wImg = R.drawable.corki_w,
                eImg = R.drawable.corki_e,
                rImg = R.drawable.corki_r,
                skinFoto = R.drawable.corki_skin,
                skinNombre = R.string.skin10
            ),
        )
    }
}